# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=30)),
                ('major', models.CharField(max_length=30)),
            ],
        ),
    ]
