# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_sazzad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveMyFirstName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('fullnam', models.CharField(max_length=30)),
            ],
        ),
    ]
