# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=50)),
            ],
        ),
    ]
