# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180309_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksub',
            name='create_time',
        ),
    ]
